Remove every NFS version except 4

diff --git a/bin/start_supervisord b/bin/start_supervisord
--- a/bin/start_supervisord
+++ b/bin/start_supervisord
@@ -1,18 +1,57 @@
 #!/bin/bash
 set -e
-set -x
+#set -x
+
+export RPCBIND_ARGS=""
+export RPC_IDMAPD_ARGS=""
+export RPC_NFSD_ARGS=""
+export RPC_NFSD_SERVER_COUNT="8"
+export RPC_MOUNTD_ARGS=""
+
+function usage {
+	echo "Usage: $0 [options] objectivefs-bucket"
+	echo "Mount an ObjectiveFS bucket and export it over NFSv4"
+	echo
+	echo -e "  -b\tArguments to rpcbind(8)"
+	echo -e "  -c\tThe number of NFS server threads. Default 8. See rpc.nfsd(8)"
+	echo -e "  -h\tThis help message"
+	echo -e "  -i\tArguments to rpc.idmapd(8)"
+	echo -e "  -n\tArguments to rpc.nfsd(8)"
+	echo -e "  -m\tArguments to rpc.mountd(8)"
+}
+
+while getopts :b:i:n:c:m:h opt; do
+	case "$opt" in
+		b) RPCBIND_ARGS="$OPTARG";;
+		i) RPC_IDMAPD_ARGS="$OPTARG";;
+		n) RPC_NFSD_ARGS="$OPTARG";;
+		c) RPC_NFSD_SERVER_COUNT="$OPTARG";;
+		m) RPC_MOUNTD_ARGS="$OPTARG";;
+		h)
+			usage
+			exit 0
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			exit 1
+			;;
+		:)
+			echo "Option -$OPTARG requires an argument." >&2
+			exit 1
+			;;
+		*)
+			echo "?? unhandled option -$OPTARG ??" >&2
+			exit 1
+			;;
+	esac
+done
+shift $((OPTIND-1))
 
 if [[ $# -ne 1 ]]; then
-	echo "Usage: $0 objectivefs-bucket" >&2
+	usage >&2
 	exit 1
 fi
 
 export OBJECTIVEFS_BUCKET="$1"
-export RPCBIND_ARGS="${RPCBIND_ARGS:-}"
-export RPC_STATD_ARGS="${RPC_STATD_ARGS:-}"
-export RPC_IDMAPD_ARGS="${RPC_IDMAPD_ARGS:-}"
-export RPC_MOUNTD_ARGS="${RPC_MOUNTD_ARGS:-}"
-export RPC_RQUOTAD_ARGS="${RPC_RQUOTAD_ARGS:-}"
-export RPC_SVCGSSD_ARGS="${RPC_SVCGSSD_ARGS:-}"
 
 exec /usr/bin/supervisord --config /etc/supervisord.conf
